# Generated by Django 6.0.5 on 2026-05-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., "Shield of BCG"', max_length=100)),
                ('story_text', models.TextField(help_text='e.g., "The hero is now protected against the invisible cough."')),
                ('is_unlocked', models.BooleanField(default=False)),
                ('date_unlocked', models.DateField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='health.childprofile')),
            ],
        ),
    ]
