# Generated by Django 6.0.5 on 2026-05-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locality',
            name='region_type',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'cm'), ('m', 'm')], default='cm', max_length=5),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g')], default='kg', max_length=5),
        ),
        migrations.AddField(
            model_name='locality',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locality',
            name='region_tag',
            field=models.CharField(choices=[('NORTH_INDIA', 'North India (Plains/Hills)'), ('SOUTH_INDIA', 'South India (Peninsular)'), ('WEST_INDIA', 'West India (Arid/Coastal)'), ('EAST_INDIA', 'East India (Plains)'), ('CENTRAL_INDIA', 'Central India (Plateau)'), ('COASTAL', 'Coastal Belt')], default='NORTH_INDIA', max_length=50),
        ),
        migrations.AddField(
            model_name='locality',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='consequence_text',
            field=models.TextField(blank=True, help_text='Specific risk if missed (e.g., Paralysis)'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='why_it_matters',
            field=models.TextField(blank=True, help_text='Educational insight for parents'),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='current_height',
            field=models.FloatField(help_text='Height (Stored in CM)'),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='current_weight',
            field=models.FloatField(help_text='Weight (Stored in KG)'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(help_text='Village/Tehsil Name', max_length=100),
        ),
    ]
