# Generated by Django 6.0.5 on 2026-05-13 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_remove_locality_region_type_childprofile_height_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostpartumCareGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('care_instructions', models.TextField()),
                ('exercise_title', models.CharField(max_length=100)),
                ('exercise_desc', models.TextField()),
                ('mental_health_tip', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostpartumDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='Day 1 to 40 of recovery')),
                ('phase', models.IntegerField(choices=[(1, 'Phase 1: Healing'), (2, 'Phase 2: Lactation'), (3, 'Phase 3: Strength')])),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_details', models.TextField()),
                ('ingredients', models.TextField(help_text='Market items required')),
                ('region_tag', models.CharField(choices=[('NORTH_INDIA', 'North India (Plains/Hills)'), ('SOUTH_INDIA', 'South India (Peninsular)'), ('WEST_INDIA', 'West India (Arid/Coastal)'), ('EAST_INDIA', 'East India (Plains)'), ('CENTRAL_INDIA', 'Central India (Plateau)'), ('COASTAL', 'Coastal Belt')], max_length=50)),
                ('benefits', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MotherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('delivery_type', models.CharField(choices=[('normal', 'Normal Delivery'), ('c-section', 'C-Section')], max_length=20)),
                ('current_weight', models.FloatField(blank=True, help_text='Stored in KG', null=True)),
                ('weight_unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g')], default='kg', max_length=5)),
                ('last_systolic_bp', models.IntegerField(blank=True, null=True)),
                ('last_diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mother_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('symptoms', models.JSONField(default=list, help_text="List of symptoms like ['fever', 'bleeding']")),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='health.motherprofile')),
            ],
        ),
    ]
