# Generated by Django 6.0.5 on 2026-05-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_postpartumcareguide_postpartumdiet_motherprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpartumdiet',
            old_name='recipe_details',
            new_name='breakfast_details',
        ),
        migrations.RenameField(
            model_name='postpartumdiet',
            old_name='recipe_name',
            new_name='breakfast_name',
        ),
        migrations.AddField(
            model_name='postpartumdiet',
            name='dinner_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postpartumdiet',
            name='dinner_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postpartumdiet',
            name='lunch_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postpartumdiet',
            name='lunch_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postpartumdiet',
            name='snack_details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postpartumdiet',
            name='snack_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postpartumdiet',
            name='ingredients',
            field=models.TextField(help_text='Consolidated market items for the day'),
        ),
    ]
