# Generated by Django 6.0.5 on 2026-05-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_rename_recipe_details_postpartumdiet_breakfast_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locality',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
