# Generated by Django 6.0.5 on 2026-05-14 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_locality_latitude_locality_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedtimeStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('template_text', models.TextField(help_text='Use [Name] and [Locality] as placeholders')),
                ('region_tag', models.CharField(choices=[('NORTH_INDIA', 'North India (Plains/Hills)'), ('SOUTH_INDIA', 'South India (Peninsular)'), ('WEST_INDIA', 'West India (Arid/Coastal)'), ('EAST_INDIA', 'East India (Plains)'), ('CENTRAL_INDIA', 'Central India (Plateau)'), ('COASTAL', 'Coastal Belt')], max_length=50)),
                ('moral_lesson', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('age_tier', models.CharField(choices=[('infant', 'Infant (0-2y)'), ('early', 'Early Childhood (3-6y)'), ('preteen', 'Pre-Teen (7-11y)')], max_length=20)),
                ('materials_needed', models.TextField(help_text='Common household items in rural India')),
                ('developmental_benefit', models.TextField()),
                ('risk_if_missed', models.TextField(blank=True, help_text='Developmental risk alert')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateField(auto_now_add=True)),
                ('parent_note', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='health.childprofile')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.offlineactivity')),
            ],
        ),
    ]
