# Generated by Django 6.0.5 on 2026-05-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_bedtimestory_offlineactivity_activitycompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherprofile',
            name='diet_preference',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian')], default='veg', max_length=20),
        ),
        migrations.AddField(
            model_name='postpartumdiet',
            name='diet_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian')], default='veg', max_length=20),
        ),
    ]
