# Generated by Django 6.0.5 on 2026-05-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_motherprofile_diet_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherprofile',
            name='allergies',
            field=models.CharField(blank=True, help_text='Comma-separated list of allergies (e.g., peanuts, dairy)', max_length=255),
        ),
    ]
