# Generated by Django 6.0.5 on 2026-05-19 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_motherprofile_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='birth_weight',
            field=models.FloatField(blank=True, help_text='Birth Weight (Stored in KG)', null=True),
        ),
        migrations.AddField(
            model_name='growthrecord',
            name='head_cm',
            field=models.FloatField(blank=True, help_text='Head Circumference in cm', null=True),
        ),
        migrations.AddField(
            model_name='motherprofile',
            name='bp_reading',
            field=models.CharField(blank=True, help_text='Historical string format BP e.g. 120/80', max_length=50),
        ),
        migrations.AddField(
            model_name='motherprofile',
            name='epds_score',
            field=models.IntegerField(blank=True, help_text='Edinburgh Postnatal Depression Scale score', null=True),
        ),
        migrations.AddField(
            model_name='motherprofile',
            name='postpartum_day',
            field=models.IntegerField(blank=True, help_text='Explicit tracked day of recovery', null=True),
        ),
        migrations.AddField(
            model_name='motherprofile',
            name='symptoms_log',
            field=models.TextField(blank=True, help_text='Raw symptom entry log'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='given_date',
            field=models.DateField(blank=True, help_text='Explicit blueprint alias for administered_date', null=True),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='vaccine_name',
            field=models.CharField(blank=True, help_text='Denormalized name for blueprint matching', max_length=100),
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('meal_type', models.CharField(max_length=50)),
                ('food_items', models.TextField()),
                ('iron_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
