# Generated by Django 6.0.5 on 2026-05-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_childprofile_birth_weight_growthrecord_head_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherprofile',
            name='pantry_items',
            field=models.TextField(blank=True, help_text='Comma-separated list of items available at home for the shopping list'),
        ),
        migrations.CreateModel(
            name='MotherExerciseMoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(choices=[('great', 'Great - Energized and Positive'), ('good', 'Good - Stable and Calm'), ('tired', 'Tired - Needs rest'), ('overwhelmed', 'Overwhelmed - Needing support')], default='good', max_length=20)),
                ('exercise_done', models.BooleanField(default=False, help_text='Did the mother complete her daily exercise/walk?')),
                ('notes', models.TextField(blank=True, help_text='Optional journal entry')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to='health.motherprofile')),
            ],
            options={
                'unique_together': {('mother', 'date')},
            },
        ),
    ]
