# Generated by Django 6.0.5 on 2026-05-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_motherprofile_pantry_items_motherexercisemoodlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherexercisemoodlog',
            name='affirmation_done',
            field=models.BooleanField(default=False, help_text='Did the mother complete her daily affirmation?'),
        ),
        migrations.AlterField(
            model_name='offlineactivity',
            name='age_tier',
            field=models.CharField(choices=[('infant', 'Infant (0-2y)'), ('early', 'Early Childhood (3-6y)'), ('preteen', 'Pre-Teen (7-11y)'), ('sensory', 'Sensory/Tracking (<6m)'), ('grasping', 'Object Permanence (6-12m)'), ('toddler', 'Toddler/Sorting (1-3y)'), ('preschool', 'Pre-schooler/Modeling (3-6y)'), ('school', 'School Support/Logic (6-11y)')], max_length=20),
        ),
    ]
