# Generated by Django 6.0.5 on 2026-05-21 16:59

import health.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_motherexercisemoodlog_affirmation_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherprofile',
            name='postpartum_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='motherprofile',
            name='priority_mode_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('kn', 'Kannada'), ('hi', 'Hindi'), ('te', 'Telugu'), ('ta', 'Tamil')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='date_of_birth',
            field=models.DateField(validators=[health.models.validate_child_age]),
        ),
    ]
