# Generated by Django 6.0.5 on 2026-05-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_motherprofile_postpartum_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Flags if the mother finished the 4-step onboarding'),
        ),
        migrations.AddField(
            model_name='motherprofile',
            name='relationship_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores hierarchy mapping and linkage rules'),
        ),
    ]
